### ISSUE TITLE
Mystery Hidden Keys between ESC > F1. F4 > F5. Maybe more.

### ISSUE THREAD

**Issue by Baa14453** [daskeyboard/daskeyboard.io#133]
Hi,
I am creating an applet and was using a row going across the F Keys.
I noticed that if my array had only two entries, only the ESC key would light up. But if I added a third entry, F1 would light up as well.

After some investigation, it appears the Daskey software thinks there is an extra key between ESC and F1, this seems to be the same for F4 and F5.

![image](https://user-images.githubusercontent.com/9057997/189765162-1f5c2df3-7f95-4180-974e-2ea2258f45db.png)

This is very weird.

**Comment by Mubramaj** [comment]
Hi,

This is by design, there is `dead` keys sometime on the board.
We basically threat the board like a matrix to be able to easily manipulate shapes and animations. 
That's why you will find dead keys like the one between escape and f1

If you place your applet on the next row, you will see the colors on the `KEY_1`
