### ISSUE TITLE
Q software does not recognize Das Keyboard 5Q

### ISSUE THREAD

**Issue by FinalDoom** [daskeyboard/daskeyboard.io#17]
As the title says, the software displays two keyboard types, both "unplugged". I'm typing this with the plugged in 5Q.

This is the case on two machines:

Windows 7 Pro, 64 bit, SP1
Q Software v1.0.0-beta.43
Latest Firmware at time of writing (firmware software detects keyboard firmware fine)

Log attached
[quio.log](https://github.com/DasKeyboard/DasKeyboard.github.io/files/2026866/quio.log)

**Comment by Foda** [comment]
Same happens to me. Seems like the 'Das Keyboard Service' crashes on start.

Win10 Insider Preview 17682
Q Software v2.0.0-beta.4
Latest Firmware

**Comment by hweisheimer** [comment]
Same issues on Win7 64-bit, with v2 beta 4 and latest firmware. Support offered workaround of launching Service Module.exe with --standalone flag, which did nothing.

**Comment by ascheschleier** [comment]
found any solution to that? I have the same problem, Firmware update went through fine. The software doesnt recognise the keyboard and the service crashes if i try to start it manually.
Windows 7 64 bit

**Comment by FinalDoom** [comment]
If you can't start it manually or with --standalone there haven't been any fixes that I've seen on the forum. There was one to change the startup registry key to move or remove the quotes in the command.. it's incorrectly quoted around the exe and the --standalone both. [One of maybe a few forum posts](https://qforum.daskeyboard.com/t/windows-10-service-execuable-wrong/1754)

I've just settled to not using the Q software, and will eventually work on the user-driven version.

I just hoped by opening a ticket it might get some developer input or attention, but the github ticketing has been silent for the last month. Transparency is seriously lacking.

**Comment by ipv1337** [comment]
This is a poorly executed product. The workaround use to work for me as annoying as that was up until a few days ago when it just stopped working all together. After funding this crap for over 3 yrs and to finally get this crap, I've lost faith in all of my kickstarter fundings. None of these guys ever take it serious with their products which is disappointing.

Now I just stop recommending or fund anything from kickstarters because of the 100% bad experiences. These guys are a joke.

**Comment by FinalDoom** [comment]
@ipv1337 I've had a good time with all my other kickstarters. A couple comic artists, a desk ergonomics thing, a couple games. It really just depends on what's being promised and delivered, and by whom. One probably could have anticipated that a hardware company promising software was probably a risky bet. Comics made by comic artists, games made by game studios, etc. are less risky because it's not uncharted.

**Comment by ascheschleier** [comment]
hehe, and a keyboard from a keyboard manufacturer? /s
yeah it is mostly the software part that is really bad now, but they still took over one and a half years longer then estamated by them to produce the main product this company produces: keyboards...

**Comment by FinalDoom** [comment]
Yeah, true. There's some stat that most kickstarters take 20% longer than anticipated to deliver, or something like that, and that's consistent with my experience--this one being the outlyer. I'd imagine that hardware manufacturing increases that delivery time by more than 20% in general.

I'm happy with the keyboard as a pretty light-up keyboard. It's just the non-functional software that I have an issue with really. But it's not too hard to reverse and write our own, it'll just take a little bit of time.

**Comment by ipv1337** [comment]
Maybe I'm just naive to the hardware projects on Kickstarter, or just really have bad luck but here are my failed purchases:

Ripple Buds (Poor quality stereo that is out of sync when paired)
Vava Dashboard Cam (Mobile app fails to connect to camera)
DAS Keyboard (Desktop app fails to run)
Boosted Board (Only decent purchase, just a year later although all the projects above were 1yr+ off target)

Perhaps you are right. Most hardware funded projects are just bad since gadgets are most of if not all my purchases...

**Comment by cjmlax** [comment]
Sorry to wake a sleeping thread, but I've received my keyboard today (Spet 12) and had a similar issue. When I plugged it in it wasn't recognized by the software, and still not after updating the firmware. I closed and opened the program a few times and then, while browsing the internet for answers, it just connected. Hopefully someone sees this because the current version of the firmware (7.4.9) seems to have resolved this bug.

**Comment by luitzifa** [comment]
I got the same Problem with my X50Q, which i received yesterday.
Edit: works after firmware upgrade. I really expect to get some hint for that but nope. Not even a working link to the firmware download page from https://q.daskeyboard.com/.

**Comment by shawila** [comment]
One day, maybe Mac/Linux users will get a firmware upgrade 🤷‍♂️

**Comment by fabiendv** [comment]
Our latest releases address these issues. 
[Changelog](https://www.daskeyboard.io/updates/changelog/) 
[Download](https://www.daskeyboard.io/get-started/software/)
