### ISSUE TITLE
Issue from website page Q Applet Development - beta

### ISSUE THREAD

**Issue by chbakouras** [daskeyboard/daskeyboard.io#54]
From URL: https://www.daskeyboard.io/applet-development/index.md

Missing documentation of qConfig into package.json
There is not a complete set of the available controlType that we can use inside the questions array. For example is there any colorpicker component?

**Comment by chbakouras** [comment]
Also there is no documentation how to install the applet to the Das Keyboard Q application.

**Comment by supercobra** [comment]
Good catch. We'll fix it.

**Comment by dnorth** [comment]
Hello @supercobra just piggybacking on this since my question seems relevant.

I followed the documentation to re-create the CPU meter Q Applet (even including the qConfig in my package.json) and am able to run the program locally.

My problem is that even though everything seems to be running successfully (getting service logs at the correct polling interval with my action and a responded 200 status) nothing is reflected on the keyboard that I am using.

So it SAYS everything is working correctly, but my keyboard lights aren't reflecting any changes and in the real-time dashboard for developers in the Q desktop app I am not seeing any signal display.

All I have done is follow the Q Applet Documentation and so I am wondering if there is another portion I am missing where connecting to my keyboard is necessary or something else. Any help is appreciated! 

(if it helps to look at my code, here is a public repo: https://github.com/dnorth/daskeyboard_cpu_monitor)

**Comment by supercobra** [comment]
@chbakouras @dnorth We are going to release a new version of the Q desktop and an update dev documentation in the next few days. The new Q desktop makes it easier to test the applet in dev mode. Keep an eye on the forum. https://qforum.daskeyboard.com/

**Comment by supercobra** [comment]
Fixed. https://www.daskeyboard.io/applet-development/

**Comment by chbakouras** [comment]
@supercobra it seems that we don't have a well-defined documentation on qConfig. A developer must search relevant DasKeyboard applets to figure out what he can use. I think that is a must to document all the options of qConfig. 
e.g. I don't know controlType components currently supported. If I need to create a new applet, I must search in another applet to figure out what is going on.

**Comment by supercobra** [comment]
@chbakouras 

For `controlType`: <https://www.daskeyboard.io/applet-development/user-questions/>
For `qConfig`: <https://www.daskeyboard.io/applet-development/>

Better?

**Comment by chbakouras** [comment]
Perfect
