### ISSUE TITLE
Issue from website page Download Das Keyboard Q Software

### ISSUE THREAD

**Issue by AppelonD** [daskeyboard/daskeyboard.io#56]
From URL: https://www.daskeyboard.io/get-started/software.md

I Need a RPM

**Comment by supercobra** [comment]
We don't have one yet. Contribution welcome!

**Comment by Cxpher** [comment]
> We don't have one yet. Contribution welcome!

I'll make an AUR pkgbuild for Arch Linux once you support the X50Q as well. 

Btw, do you have the path locations for where all the files in the deb should be placed officially?

I can also make an RPM but again only once the Linux build is properly supported with X50Q support in as well. Otherwise it wouldn't be wise to place them in any repos.

**Comment by supercobra** [comment]
@AppelonD Thank you for contributing the RPM package. Users can get it from there: https://www.daskeyboard.io/get-started/software/
