### ISSUE TITLE
MacOS: App cannot be checked for malicious software

### ISSUE THREAD

**Issue by tFable** [daskeyboard/daskeyboard.io#97]
Hello,

On Q Software version 3.2.8 for Mac, on MacOS 11.2.3, the following message is shown when first trying to run the software.

![Screen Shot 2021-04-09 at 6 22 09 PM](https://user-images.githubusercontent.com/37750209/114249776-29608180-9961-11eb-921e-3e8ac32d1031.png)

While this can be bypassed via System Preferences --> Security and Privacy --> General --> Open Anyway, it is not ideal.

Thanks

**Comment by jeffreystrauss** [comment]
Upvoting this. Would rather not have to adjust my system security settings to install this, if it can be avoided.

**Updating my comment**: This issue is addressed in the Das Keyboard 5QS User Manual. _"The reason this warning shows is because Apple will not provide notarization for the software because applets use open-source software, and Apple does not support open-source software. The software is not malicious in any way and applets go through a rigorous review process before approval."_

**Comment by SubtleCo** [comment]
I'm on an M1 / Big Sur, and I'm actually blocked as even the "Open Anyway" button still prompts me with the same error
